version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - backend
    ports:
      - "59019:59019"
    depends_on:
      - "db"
    restart: unless-stopped
  db:
    image: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  db-volume:
